// scripts/embed-assets.ts
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join, extname } from "path";

const assetsDir = "./assets"; // 你的原始图片目录
const outputFile = "./src/module/generated-assets.ts";

// 确保输出目录存在
if (!existsSync("./src")) mkdirSync("./src", { recursive: true });
const files = readdirSync(assetsDir, { recursive: true }) as string[];
let dictContent = `// Auto-generated by embed-assets.ts\nexport const assetsMap: Record<string, { mime: string; data: string }> = {\n`;
const extensions = [".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".ico"];

for (const file of files) {
    const fullPath = join(assetsDir, file);
    const ext = extname(fullPath).toLowerCase();
    if (extensions.includes(ext)) {
        const data = readFileSync(fullPath);
        const base64 = Buffer.from(data).toString("base64");
        // 生成前端请求时使用的 URL Path，例如 /assets/logo.png
        const urlPath = `/${fullPath.replace(/\\/g, '/')}`;
        // 获取 MIME 类型
        const mime = ext === ".svg" ? "image/svg+xml" : `image/${ext.replace('.', '')}`;
        dictContent += `  "${urlPath}": { mime: "${mime}", data: "data:${mime};base64,${base64}" },\n`;
    }
}

dictContent += `};\n`;
writeFileSync(outputFile, dictContent);
console.log(`✅ Embedded assets generated at ${outputFile}`);